### ISSUE TITLE
UMAP reference

### ISSUE THREAD

**Issue by lmcinnes** [greenelab/czi-hca-report#5]
Hi,

I wanted to say that this looks like fascinating work in progress, and I will be very interested to see further outcomes. As a minor point I would appreciate it if you could include a reference to the original UMAP paper (https://arxiv.org/abs/1802.03426). The paper by Becht et al. is excellent, and certainly a great reference so please don't remove it, but the arxiv paper is probably the correct reference for the technique/algorithm itself.

**Comment by cgreene** [comment]
Hi @lmcinnes - this is a great point! Definitely the original UMAP paper should also be cited. Thanks! 👍

**Comment by cgreene** [comment]
Noting that @huqiwen0313 filed #6 that should close this. Just waiting for the build to complete to review that. Wanted to link the issue/PR together. 😄

**Comment by huqiwen0313** [comment]
Thanks a lot for the suggestion. We have added umap reference.
